### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Tymsx** [Jasmine969/WechatVisualization#1]
您好，感谢您的开源项目，使用后发现生成的图片中，两人的个人专属词条和表情，除颜色，方向外其他均相同，不知是否为操作问题，再次感谢！

**Comment by Jasmine969** [comment]
谢谢你的反馈。我有两个问题。
1. 专属性的度量值也完全一样吗？
2. 把top_k设置大一点看看会不会有区别？

**Comment by Tymsx** [comment]
更改top_k值后双方的词条同时增多，还是保持相同
![44048144364c494bf3436097e0b98bc](https://github.com/Jasmine969/WechatVisualization/assets/155798803/920f163d-9c21-4bd0-a976-ad198cec0cab)
![0621a612c82deed29952279b4001dc4](https://github.com/Jasmine969/WechatVisualization/assets/155798803/294d00db-4499-49e4-90ad-c378fe49e9f8)

**Comment by Jasmine969** [comment]
是个bug。三小时内给你修复。

**Comment by Jasmine969** [comment]
已修复。感谢反馈！

**Comment by Tymsx** [comment]
还有一个是“时域处理”的报错，我刚开始认为是excel里的格式不对，我改了之后，报出了同类型的错误。大佬有空帮忙看一下
![eadf4e990a31bef70c9ad853d4b994f](https://github.com/Jasmine969/WechatVisualization/assets/155798803/6a9e4ac1-387b-48c3-a238-4be998ded584)
![6b4b42d4c7cda7e6c98a0f454866a43](https://github.com/Jasmine969/WechatVisualization/assets/155798803/ab7cb02c-ab8a-4f9a-9f30-5c3e0369aa8d)
![2160e4159d70eaaa0c877eccd02c07a](https://github.com/Jasmine969/WechatVisualization/assets/155798803/541525dc-c5d9-409b-a244-a1472b04e8b7)

**Comment by Jasmine969** [comment]
应该是改成月/日/年的格式啊，你的表格StrTime是年/月/日

**Comment by Tymsx** [comment]
![ed8fb62b11820d21176151f2d70bf63](https://github.com/Jasmine969/WechatVisualization/assets/155798803/9812af89-e1df-48c2-b752-144a9e211fbd)
![a29c5890fe6cf4242643be7904399a1](https://github.com/Jasmine969/WechatVisualization/assets/155798803/d0b0561c-791a-4f12-8962-b45a5fa7e75b)

**Comment by Jasmine969** [comment]
刚刚改进了几行代码，可以读取任意时间格式。现在应该不用特意设置时间格式了。您再看看！

**Comment by Tymsx** [comment]
大佬，一个小小的问题，生成的时域处理图时间顺序有点问题
![f0f00eeaff8207ac5269e5ffc48215e](https://github.com/Jasmine969/WechatVisualization/assets/155798803/ffd15c53-5218-4dab-8e83-a8ca179798e8)
![70c25eb12be8f48372b70a1e44567bf](https://github.com/Jasmine969/WechatVisualization/assets/155798803/c70f0e8a-a3ec-4467-9332-b9c097b3b338)

**Comment by Jasmine969** [comment]
太尴尬了，我比较马虎。刚刚又修改了一下，你再看看？

**Comment by Tymsx** [comment]
ok，大佬太强啦，感谢大佬！！！
