### ISSUE TITLE
indexerror

### ISSUE THREAD

**Issue by xuelixunhua** [Jasmine969/WechatVisualization#2]
File "c:\Users\xueli\baidu\BaiduSyncdisk\python_file\normal_coding\WechatVisualization-master\main.py", line 28, in main
    parse(msg_file, emoji_file, stopword_file, transform_file, user_dict_file, process_rows)
  File "c:\Users\xueli\baidu\BaiduSyncdisk\python_file\normal_coding\WechatVisualization-master\parse.py", line 55, in parse
    if result[ind2 - 2] != '[':
IndexError: list index out of range
![Uploading 屏幕截图 2024-03-21 105556.png…]()

**Comment by Jasmine969** [comment]
我不知道您具体出错在哪一行，导致出错的那条消息文字是什么，因此不好解决。
为此我刚刚更新了代码，可以在parse.py报IndexError时显示出错的行数，您重新下载一下，然后运行。然后确定出错的行数。
看看那一行是什么文本？

**Comment by xuelixunhua** [comment]
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\xueli\AppData\Local\Temp\jieba.cache
Loading model cost 0.376 seconds.
Prefix dict has been built successfully.
 18%|█████████████████▉                                                                                  | 216927/1212395 [00:35<02:47, 5953.72it/s]
数据文件第217113行有问题
 18%|█████████████████▉                                                                                  | 217113/1212395 [00:35<02:42, 6131.42it/s] 
Traceback (most recent call last):
  File "c:\Users\xueli\baidu\BaiduSyncdisk\python_file\normal_coding\WechatVisualization-master\parse.py", line 56, in parse
    _ = result[ind2 - 2]
IndexError: list index out of range

pirnt出来这个附近的行：
df = pd.read_csv('input_data/messages.csv')
print(df.iloc[217110:217115])
localId  TalkerId   Type  SubType  IsSender  ...                           StrContent              StrTime Remark    NickName Sender
217110   217542       268      1        0         0  ...                     爆个照再去学吧，我们给你安排对象  2022-09-27 14:48:44    NaN  北京交友玩乐群
3️⃣  晚上吃啥～
217111   217543       268      1        0         0  ...                     爆个照再去学吧，我们给你安排对象  2022-09-27 14:48:50    NaN  北京交友玩乐群
3️⃣     何夕
217112   217544       268      1        0         0  ...                     爆个照再去学吧，我们给你安排对象  2022-09-27 14:48:58    NaN  北京交友玩乐群
3️⃣   奶昔奈司
217113   217545       268     49       57         0  ...                                  NaN  2022-09-27 14:49:03    NaN  北京交友玩乐群3️⃣      苏     
217114   217546       268  10000        0         0  ...  <revokemsg>"槐序" 撤回了一条消息</revokemsg>  2022-09-27 14:49:08    NaN  北京交友玩乐群3️⃣    
 槐序

[5 rows x 12 columns]

**Comment by Jasmine969** [comment]
@xuelixunhua 大哥，你把上面这段用CSV上传吧
```python
df_bug = records.loc[i, :]
df_bug.to_csv('bug.csv', index=None, encoding='utf_8_sig')
```

**Comment by xuelixunhua** [comment]
[bug.csv](https://github.com/Jasmine969/WechatVisualization/files/14719583/bug.csv)

**Comment by Jasmine969** [comment]
用你提交的csv没有发现任何问题啊。你再用我刚刚更新的代码试试看？可能会报错，会自动生成bug.csv。提交bug.csv

**Comment by xuelixunhua** [comment]
[bug.csv](https://github.com/Jasmine969/WechatVisualization/files/14730619/bug.csv)

**Comment by Jasmine969** [comment]
我想这次应该是修复了，你再看看我新提交的代码？
