### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by xuelixunhua** [Jasmine969/WechatVisualization#3]
我理解支持的是A与B的聊天记录，比如我提取了全部的聊天记录，这里是没有区别的。
能否增加功能，在全部聊天记录里先筛选出目标聊天人，我看提取出来的messages里面有Remark、NickName这种字段，应该可以实现的。比如我用的是全部聊天记录，只筛选出与name1、name2有关的记录进行分析

**Comment by Jasmine969** [comment]
这个不难，无论是用excel还是用pandas，操作都很简单，用户可以自行筛选。

而且和不同人的聊天记录可能要设定不同的top_k, min_count等参数，设定起来也麻烦一点。我觉得不如对name1和name2分两次操作更方便。
