### ISSUE TITLE
报错无法解决

### ISSUE THREAD

**Issue by hydeng2022** [Jasmine969/WechatVisualization#7]
这两个报错反复出现报错，百度没有解决问题，来打扰一下大佬
![Snipaste_2024-12-27_15-47-05](https://github.com/user-attachments/assets/4dcf4446-2577-40b2-a3ef-e904b2de76ca)

![Snipaste_2024-12-27_15-48-34](https://github.com/user-attachments/assets/51644921-998e-4bc7-b089-75768c1c3113)

**Comment by Jasmine969** [comment]
请提供能够复现你的问题的excel表

**Comment by hydeng2022** [comment]
[msg.zip](https://github.com/user-attachments/files/18259229/msg.zip)

**Comment by Jasmine969** [comment]
我用你的数据没有报错。你是否改动了emoji.txt？你试试用我的msg.xlsx，看看会不会报错。

**Comment by hydeng2022** [comment]
emoji.txt成空的了，重新下载之后好了，感谢大佬
